seml:
  name: rgnn_at_scale_attack_evasion_global_transfer
  executable: experiments/experiment_global_attack_transfer.py
  project_root_dir: ../..
  output_dir: seml/attack_evasion_global_transfer/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-08:00     # max time, D-HH:MM
    # partition: gpu_large

fixed:
  epsilons: [0, 0.01, 0.05, 0.1, 0.25]
  surrogate_params:
    n_filters: 64
    dropout: 0.5
    train_params:
      lr: 1e-2
      weight_decay: 1e-3
      patience: 100
      max_epochs: 3000
  artifact_dir: cache
  pert_adj_storage_type: evasion_transfer_attack_adj
  pert_attr_storage_type: evasion_transfer_attack_attr
  model_storage_type: pretrained
  device: 0
  data_device: 0 
  binary_attr: False

grid:
  dataset:
    type: choice
    options:
      - ogbn-arxiv

  seed:
    type: choice
    options:
      - 0
      - 1
      - 5

greedy_rbcd:
  fixed:
    attack: GreedyRBCD
  grid: 
    attack_params:
      type: parameter_collection
      params:
        loss_type: 
          type: choice
          options:
            # - CE
            - MCE

prbcd:
  fixed:
    attack: PRBCD
    attack_params:
      keep_heuristic: WeightOnly
      search_space_size: 5_000_000
      do_synchronize: True
  grid: 
    attack_params:
      type: parameter_collection
      params:
        loss_type: 
          type: choice
          options:
            # - CE
            - tanhMargin

# gang:
#   fixed:
#     attack: GANG
#     attack_params:
#       edge_with_random_reverse: False
#       edge_step_size: 100
#       edge_budget: 1000
#       feature_dedicated_iterations: 5
#       do_synchronize: True
#       eps: 1e-16

dice:
  fixed:
    attack: DICE