seml:
  name: rgnn_at_scale_attack_evasion_transfer_vs_number_nodes
  db_collection: kdd21_rgnn_at_scale_attack_evasion_transfer_vs_number_nodes
  executable: experiment_attack_evasion_transfer_vs_number_nodes.py
  conda_environment: rgnn_at_scale
  project_root_dir: ../..
  output_dir: seml/attack_evasion_transfer_vs_number_nodes/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-01:00     # max time, D-HH:MM

fixed:
  epsilons: [0, 0.01, 0.05, 0.1, 0.25]
  surrogate_params:
    n_filters: 64
    dropout: 0.5
    train_params:
      lr: 1e-2
      weight_decay: 1e-3
      patience: 100
      max_epochs: 3000
  artifact_dir: cache
  pert_adj_storage_type: evasion_transfer_attack_vs_number_nodes_adj
  pert_attr_storage_type: evasion_transfer_attack_vs_number_nodes_attr
  device: 0
  binary_attr: False

  n_classes: 8

grid:
  dataset:
    type: choice
    options:
      - ogbn-arxiv

  seed:
    type: range
    min: 0
    max: 500
    step: 1

# greedy_rbcd:
#   fixed:
#     attack: GreedyRBCD
#   grid: 
#     attack_params:
#       type: parameter_collection
#       params:
#         loss_type: 
#           type: choice
#           options:
#             - CE
#             - MCE

prbcd:
  fixed:
    attack: PRBCD
    attack_params:
      keep_heuristic: WeightOnly
      search_space_size: 5_000_000
      do_synchronize: True
  grid: 
    attack_params:
      type: parameter_collection
      params:
        loss_type: 
          type: choice
          options:
            # - CE
            - tanhCW
    use_largest_component:
      type: choice
      options:
        - True
        - False
