base:
  name: papers_localprbcd
  executable: experiments/experiment_local_attack_direct.py
  project_root_dir: ../..
  output_dir: config/attack_evasion_local_direct/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 380G          # memory
    cpus-per-task: 4  # num cores
    time: 1-00:00     # max time, D-HH:MM

fixed:
  data_dir: datasets
  dataset: ogbn-papers100M
  binary_attr: False
  min_node_degree: None
  nodes_topk: 40
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0
  data_device: cpu
  debug_level: info
  make_undirected: False
  attack_params.epochs: 20
  attack_params.display_step: 1
  attack_params.fine_tune_epochs: 10
  attack_params.do_synchronize: True
  attack_params.ppr_recalc_at_end: True
  attack_params.ppr_cache_params:
    data_artifact_dir: cache
    data_storage_type: ppr

grid:
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5
  epsilons:
    type: choice
    options:
      - [0.05]
      - [0.1]
      - [0.25]
      - [0.5]
      - [1.0]


localprbcd_pprgo_vanilla:
  fixed:
    attack: LocalBatchedPRBCD
    model_label: Vanilla PPRGo
    attack_params.loss_type: Margin
    attack_params.search_space_size: 2_500
    attack_params.lr_factor: 1e-1


localprbcd_pprgo_median10:
  fixed:
    attack: LocalBatchedPRBCD
    model_label: Soft Median PPRGo (T=10.0)
    attack_params.loss_type: Margin
    attack_params.search_space_size: 2_500
    attack_params.lr_factor: 1e-1


localprbcd_pprgo_median20:
  fixed:
    attack: LocalBatchedPRBCD
    model_label: Soft Median PPRGo (T=20.0)
    attack_params.loss_type: Margin
    attack_params.search_space_size: 2_500
    attack_params.lr_factor: 1e-1


localprbcd_pprgo_median50:
  fixed:
    attack: LocalBatchedPRBCD
    model_label: Soft Median PPRGo (T=50.0)
    attack_params.loss_type: Margin
    attack_params.search_space_size: 2_500
    attack_params.lr_factor: 1e-1


localprbcd_pprgo_median100:
  fixed:
    attack: LocalBatchedPRBCD
    model_label: Soft Median PPRGo (T=100.0)
    attack_params.loss_type: Margin
    attack_params.search_space_size: 2_500
    attack_params.lr_factor: 1e-1


localprbcd_pprgo_median200:
  fixed:
    attack: LocalBatchedPRBCD
    model_label: Soft Median PPRGo (T=200.0)
    attack_params.loss_type: Margin
    attack_params.search_space_size: 2_500
    attack_params.lr_factor: 1e-1


localprbcd_pprgo_median500:
  fixed:
    attack: LocalBatchedPRBCD
    model_label: Soft Median PPRGo (T=500.0)
    attack_params.loss_type: Margin
    attack_params.search_space_size: 2_500
    attack_params.lr_factor: 1e-1


