seml:
  name: arxiv_rgnn_at_scale_train
  executable: experiments/experiment_train.py
  project_root_dir: ../..
  output_dir: config/train/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-12:00     # max time, D-HH:MM

fixed:
  train_params:
    lr: 1e-2
    weight_decay: 0
    patience: 300
    max_epochs: 3000
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0
  data_device: cpu
  make_undirected: True
  binary_attr: False

  dataset: ogbn-arxiv

grid:      
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5

gcn:
  fixed:
    model_params:
      label: Vanilla GCN
      model: GCN
      dropout: 0.5
      n_filters: [256, 256]
      gdc_params: None
      svd_params: None
      jaccard_params: None
      with_batch_norm: True

gdc:
  fixed:
    model_params:
      label: Vanilla GDC
      model: GCN
      dropout: 0.5
      n_filters: [256, 256]
      gdc_params:
          alpha: 0.1
          k: 64
          use_cpu: True
      svd_params: None
      jaccard_params: None
      with_batch_norm: True

soft_medoid_gdc_t0_5:
  fixed:
    model_params:
      label: Soft Medoid GDC (T=0.5)
      model: RGNN
      dropout: 0.5
      n_filters: 64
      mean: soft_k_medoid
      mean_kwargs:
          k: 64
          temperature: 0.5
      gdc_params:
          alpha: 0.1
          k: 64
          use_cpu: True
      do_checkpoint: True
      do_normalize_adj_once: True
      n_chunks: 32
      svd_params: None
      jaccard_params: None
      with_batch_norm: True

soft_medoid_gdc_t5:
  fixed:
    model_params:
      label: Soft Medoid GDC (T=5.0)
      model: RGNN
      dropout: 0.5
      n_filters: 64
      mean: soft_k_medoid
      mean_kwargs:
          k: 64
          temperature: 5
      gdc_params:
          alpha: 0.1
          k: 64
          use_cpu: True
      do_checkpoint: True
      do_normalize_adj_once: True
      n_chunks: 32
      svd_params: None
      jaccard_params: None
      with_batch_norm: True
