seml:
  name: sgc_arxiv
  executable: experiments/experiment_train.py
  project_root_dir: ../..
  output_dir: config/train/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-00:30     # max time, D-HH:MM
    # partition: cpu
    qos: studentprio
    #qos: interactive
    # qos: studentpriocpu

fixed:
  data_dir: data/
  train_params:
    patience: 300
    max_epochs: 5000
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0
  data_device: 0
  make_undirected: True
  binary_attr: False

grid:
  dataset:
    type: choice
    options:
      - ogbn-arxiv
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5

sgc:
  fixed:
    model_params:
      label: Vanilla SGC
      model: SGC
      K: 2
      cached: True
    train_params:
      lr: 1e-2
      weight_decay: 1e-7

