seml:
  name: rgnn_at_scale_train
  executable: experiments/experiment_train.py
  project_root_dir: ../..
  output_dir: config/train/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 64G
    cpus-per-task: 4  # num cores
    time: 0-05:00     # max time, D-HH:MM
    #qos: interactive

fixed:
  data_dir: datasets
  train_params:
    patience: 300
    max_epochs: 3000
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0
  data_device: cpu
  make_undirected: True
  binary_attr: False
  dataset: citeseer

grid:
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5
      # - 42
      # - 100


pprgo:
  fixed:
    model_params:
      label: Vanilla PPRGo
      model: PPRGo
      ppr_normalization: 'row' 
      batch_norm: False
      topk: 64
      hidden_size: 64
      nlayers: 2
      alpha: 0.203183
      eps: 1e-3
      dropout: 0.1
    train_params:
      lr: 1e-3
      weight_decay: 1e-2


soft_medoid_rpprgo_t1_0:
  fixed:
    model_params:
      label: Soft Medoid RPPRGo (T=1.0)
      model: RobustPPRGo
      ppr_normalization: 'row' 
      batch_norm: False
      topk: 64
      hidden_size: 64
      nlayers: 2
      alpha: 0.196717
      eps: 1e-3
      dropout: 0.5
      mean: soft_k_medoid
      mean_kwargs: 
        k: 64
        temperature: 1.0
        with_weight_correction: True
    train_params:
      lr: 1e-3
      weight_decay: 1e-2


soft_medoid_rpprgo_t0_5:
  fixed:
    model_params:
      label: Soft Medoid RPPRGo (T=0.5)
      model: RobustPPRGo
      ppr_normalization: 'row' 
      batch_norm: False
      topk: 64
      hidden_size: 128
      nlayers: 2
      alpha: 0.166807
      eps: 1e-3
      dropout: 0.1
      mean: soft_k_medoid
      mean_kwargs: 
        k: 64
        temperature: 0.5
        with_weight_correction: True
    train_params:
      lr: 1e-2
      weight_decay: 1e-2


soft_medoid_rpprgo_t0_2:
  fixed:
    model_params:
      label: Soft Medoid RPPRGo (T=0.2)
      model: RobustPPRGo
      ppr_normalization: 'row' 
      batch_norm: False
      topk: 64
      hidden_size: 64
      nlayers: 2
      alpha: 0.069915
      eps: 1e-3
      dropout: 0.5
      mean: soft_k_medoid
      mean_kwargs: 
        k: 64
        temperature: 0.2
        with_weight_correction: True
    train_params:
      lr: 1e-3
      weight_decay: 1e-2


soft_median_rpprgo_t1_0:
  fixed:
    model_params:
      label: Soft Median RPPRGo (T=1.0)
      model: RobustPPRGo
      ppr_normalization: 'row' 
      batch_norm: False
      topk: 64
      hidden_size: 64
      nlayers: 2
      alpha: 0.147924
      eps: 1e-3
      dropout: 0.5
      mean: soft_median
      mean_kwargs: 
        temperature: 1.0
    train_params:
      lr: 1e-2
      weight_decay: 1e-2


soft_median_rpprgo_t0_5:
  fixed:
    model_params:
      label: Soft Median RPPRGo (T=0.5)
      model: RobustPPRGo
      ppr_normalization: 'row' 
      batch_norm: False
      topk: 64
      hidden_size: 128
      nlayers: 2
      alpha: 0.179727
      eps: 1e-3
      dropout: 0.1
      mean: soft_median
      mean_kwargs: 
        temperature: 0.5
    train_params:
      lr: 1e-2
      weight_decay: 1e-2


soft_median_rpprgo_t0_2:
  fixed:
    model_params:
      label: Soft Median RPPRGo (T=0.2)
      model: RobustPPRGo
      ppr_normalization: 'row' 
      batch_norm: False
      topk: 64
      hidden_size: 64
      nlayers: 2
      alpha: 0.136218
      eps: 1e-3
      dropout: 0.5
      mean: soft_median
      mean_kwargs: 
        temperature: 0.2
    train_params:
      lr: 1e-3
      weight_decay: 1e-2