seml:
  name: rgnn_at_scale_train
  executable: experiments/experiment_train.py
  project_root_dir: ../..
  output_dir: config/train/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-01:00     # max time, D-HH:MM

fixed:
  #data_dir: data
  train_params:
    lr: 1e-1
    weight_decay: 2e-5
    patience: 300
    max_epochs: 3000
  artifact_dir: cache_debug
  model_storage_type: pretrained
  device: 0
  data_device: 0
  make_undirected: True
  binary_attr: False
  feat_norm: False

grid:
  dataset:
    type: choice
    options:
      # - cora_ml
      # - citeseer
      # - ogbn-products
      - pubmed
      #- ogbn-arxiv

  seed:
    type: choice
    options:
      - 0
      # - 1
      # - 5

sgc:
  fixed:
    model_params:
      label: Vanilla SGC
      model: SGC
      K: 2
      dropout: 0.5

