seml:
  name: sgc_cora_citeseer
  executable: experiments/experiment_train.py
  project_root_dir: ../..
  output_dir: config/train/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-00:10     # max time, D-HH:MM
    # partition: cpu
    qos: studentprio
    #qos: interactive
    # qos: studentpriocpu


fixed:
  #data_dir: data
  train_params:
    patience: 300
    max_epochs: 3000
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0
  data_device: 0
  make_undirected: True
  binary_attr: False

grid:
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5

sgc_cora:
  fixed:
    dataset: cora_ml
    train_params:
      lr: 0.2
      weight_decay: 1.3026973714043257e-05 # official value
    model_params:
      label: Vanilla SGC
      model: SGC
      K: 2
      cached: True


sgc_citeseer:
  fixed:
    dataset: citeseer
    train_params:
      lr: 0.2
      weight_decay: 2.3545587233182368e-05 # official value
    model_params:
      label: Vanilla SGC
      model: SGC
      K: 2
      cached: True

