seml:
  name: rgnn_products_train
  executable: experiments/experiment_train.py
  project_root_dir: ../..
  output_dir: seml/train/output


slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 80G          # memory
    cpus-per-task: 4  # num cores
    time: 1-12:00     # max time, D-HH:MM
    partition: gpu_large

fixed:
  data_dir: datasets
  dataset: ogbn-products
  binary_attr: False
  make_undirected: True
  train_params:
    max_epochs: 50
    patience: 300
  artifact_dir: cache
  model_storage_type: victim_products_simon
  device: 0
  data_device: cpu
  ppr_cache_params:
    data_artifact_dir: cache
    data_storage_type: ppr

grid:
  seed: 
    type: choice
    options:
      - 0
      - 1
      - 5

  model_params.alpha:
    type: choice
    options:
      # - 0.01
      # - 0.05
      - 0.1
  model_params.hidden_size:
    type: choice
    options:
      # - 256
      - 512
      # - 768
  model_params.nlayers:
    type: choice
    options:
      # - 3
      - 4
      # - 5
      # - 6
      # - 7

  train_params:
    type: parameter_collection 
    params:
      optim:
        type: choice
        options: 
          - Adam
          #- SGD
      lr:
        type: choice
        options: 
          #- 1e-1
          #- 5e-2
          - 1e-2
          #- 5e-3
          #- 2e-3
          #- 1e-3
          #- 5e-4
          #- 1e-4
      weight_decay:
        type: choice
        options:
          - 0
          # - 1e-4
          # - 1e-6
          #- 5e-6
          # - 1e-5
          # - 2e-5
          #- 5e-5
          #- 8e-5
      dropout:
        type: choice
        options:
          - 0
          # - 0.1
          # - 0.25
      use_annealing_scheduler: 
        type: choice
        options:
          #- True
          - False
      scheduler_warm_restarts: 
        type: choice
        options:
          #- True
          - False
      annealing_scheduler_T_0: 
        type: choice
        options:
          # - 2
          - 5
          #- 10
          # - 20
      scheduler_step:
        type: choice
        options:
          - 60
      scheduler_time:
        type: choice
        options:
          - epoch
          #- batch

# pprgo:
#   fixed:
#     model_params:
#       # label: Vanilla PPRGo Diffuse Embeddings
#       # model: PPRGoDiffEmbWrapper
#       label: Vanilla PPRGo
#       model: PPRGo
#       topk: 128
#       eps: 1e-5
#       ppr_normalization: row
#       # hidden_size: 512
#       # nlayers: 4
#       # alpha: 0.1
#       batch_norm: True
#     train_params:
#       # lr: 1e-2
#       # weight_decay: 0
#       batch_size: 8192 # 20480 #16384 # 3072 # 2048 # 3072 #4096 # 8192
#       batch_mult_val: 1
#       forward_batch_size: 1024



# soft_median_1_0_pprgo:
#   fixed:
#     model_params:
#       # label: Soft Median PPRGo Diffuse Embeddings (T=1.0)
#       # model: RobustPPRGoDiffEmb # RobustPPRGo
#       label: Soft Median PPRGo (T=1.0)
#       model: RobustPPRGo
#       topk: 64
#       eps: 1e-4
#       ppr_normalization: row
#       #alpha: 0.11
#       batch_norm: True
#       #dropout: 0.0
#       #hidden_size: 256
#       #nlayers: 3
#       mean: soft_median
#       mean_kwargs: 
#         temperature: 1.0
#     train_params:
#       #lr: 1e-3
#       #weight_decay: 0
#       batch_size: 10240 # 8192 #10240 #16384 #10240 # 3072 # 2048 # 6144 #4096 # 8192
#       batch_mult_val: 1
#       forward_batch_size: 512

# soft_median_XX_pprgo:
#   grid:
#     model_params.mean_kwargs.temperature: 
#     type: choice
#     options:
#       - 5.0
#       - 10.0
#       - 20.0
#       - 50.0
#       - 100.0
#   fixed:
#     model_params:
#       # label: Soft Median PPRGo Diffuse Embeddings (T=5.0)
#       # model: RobustPPRGoDiffEmb # RobustPPRGo
#       label: Soft Median PPRGo (T=X)
#       model: RobustPPRGo
#       topk: 128
#       eps: 1e-5
#       ppr_normalization: row
#       #alpha: 0.11
#       batch_norm: True
#       #dropout: 0.0
#       #hidden_size: 256
#       #nlayers: 3
#       mean: soft_median
#     train_params:
#       #lr: 1e-3
#       #weight_decay: 0
#       batch_size: 2048 # 8192 #10240 #16384 #10240 # 3072 # 2048 # 6144 #4096 # 8192
#       batch_mult_val: 1
#       forward_batch_size: 512

soft_median_5_0_pprgo:
  fixed:
    model_params:
      # label: Soft Median PPRGo Diffuse Embeddings (T=5.0)
      # model: RobustPPRGoDiffEmb # RobustPPRGo
      label: Soft Median PPRGo (T=5.0)
      model: RobustPPRGo
      topk: 128
      eps: 1e-5
      ppr_normalization: row
      #alpha: 0.11
      batch_norm: True
      #dropout: 0.0
      #hidden_size: 256
      #nlayers: 3
      mean: soft_median
      mean_kwargs:
        temperature: 5
    train_params:
      #lr: 1e-3
      #weight_decay: 0
      batch_size: 2048 # 8192 #10240 #16384 #10240 # 3072 # 2048 # 6144 #4096 # 8192
      batch_mult_val: 1
      forward_batch_size: 512

soft_median_10_0_pprgo:
  fixed:
    model_params:
      # label: Soft Median PPRGo Diffuse Embeddings (T=5.0)
      # model: RobustPPRGoDiffEmb # RobustPPRGo
      label: Soft Median PPRGo (T=10.0)
      model: RobustPPRGo
      topk: 128
      eps: 1e-5
      ppr_normalization: row
      #alpha: 0.11
      batch_norm: True
      #dropout: 0.0
      #hidden_size: 256
      #nlayers: 3
      mean: soft_median
      mean_kwargs:
        temperature: 10
    train_params:
      #lr: 1e-3
      #weight_decay: 0
      batch_size: 2048 # 8192 #10240 #16384 #10240 # 3072 # 2048 # 6144 #4096 # 8192
      batch_mult_val: 1
      forward_batch_size: 512

soft_median_20_0_pprgo:
  fixed:
    model_params:
      # label: Soft Median PPRGo Diffuse Embeddings (T=5.0)
      # model: RobustPPRGoDiffEmb # RobustPPRGo
      label: Soft Median PPRGo (T=20.0)
      model: RobustPPRGo
      topk: 128
      eps: 1e-5
      ppr_normalization: row
      #alpha: 0.11
      batch_norm: True
      #dropout: 0.0
      #hidden_size: 256
      #nlayers: 3
      mean: soft_median
      mean_kwargs:
        temperature: 20
    train_params:
      #lr: 1e-3
      #weight_decay: 0
      batch_size: 2048 # 8192 #10240 #16384 #10240 # 3072 # 2048 # 6144 #4096 # 8192
      batch_mult_val: 1
      forward_batch_size: 512

soft_median_30_0_pprgo:
  fixed:
    model_params:
      # label: Soft Median PPRGo Diffuse Embeddings (T=5.0)
      # model: RobustPPRGoDiffEmb # RobustPPRGo
      label: Soft Median PPRGo (T=30.0)
      model: RobustPPRGo
      topk: 128
      eps: 1e-5
      ppr_normalization: row
      #alpha: 0.11
      batch_norm: True
      #dropout: 0.0
      #hidden_size: 256
      #nlayers: 3
      mean: soft_median
      mean_kwargs:
        temperature: 30
    train_params:
      #lr: 1e-3
      #weight_decay: 0
      batch_size: 2048 # 8192 #10240 #16384 #10240 # 3072 # 2048 # 6144 #4096 # 8192
      batch_mult_val: 1
      forward_batch_size: 512