seml:
  name: rgnn_at_scale_train
  executable: experiment_train.py
  project_root_dir: ../..
  output_dir: seml/train/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-00:05     # max time, D-HH:MM

fixed:
  data_dir: /nfs/students/schmidtt/datasets/
  train_params:
    lr: 1e-2
    weight_decay: 1e-3
    patience: 300
    max_epochs: 100
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0


grid:
  dataset:
    type: choice
    options:
      - cora_ml
      - citeseer
  binary_attr:
    type: choice
    options:
      #- True
      - False
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5

random:
  samples: 100
  model_params:
    type: parameter_collection 
    params:
      hidden_size:              # Size of the MLP's hidden layer
        type: choice
        options: [160, 128, 64, 32]
      nlayers:                   # Number of MLP layers
        type: choice
        options: [2]
      alpha:                      # PPR teleport probability
        type: choice
        options: [0.25, 0.1]
      # mean_kwargs: 
      #   type: parameter_collection 
      #   params:
      #     temperature: 
      #       type: choice
      #       options: [0.2, 0.5, 1.0, 5.0, 20.0, 50.0]
      dropout:                      
        type: choice
        options: [0.1, 0.25, 0.5]


pprgo:
  fixed:
    model_params:
      label: Vanilla PPRGo
      model: PPRGo
      ppr_normalization: 'row' 
      do_cache_adj_prep: True
      topk: 64
      eps: 1e-2
    train_params:
      batch_size: 65536
      batch_mult_val: 1
    data_device: cpu
