seml:
  name: rgnn_at_scale_train
  executable: experiments/experiment_train.py
  project_root_dir: ../..
  output_dir: seml/train/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 48G          # memory
    cpus-per-task: 4  # num cores
    time: 1-00:00     # max time, D-HH:MM

fixed:
  data_dir: datasets
  train_params:
    lr: 1e-2
    weight_decay: 0
    patience: 300
    max_epochs: 3000
    batch_mult_val: 1
    batch_size: 2048
    forward_batch_size: 512
  artifact_dir: cache
  model_storage_type: pretrained_pprgo
  device: 0
  data_device: 0 
  make_undirected: True
  binary_attr: False

  dataset: ogbn-products

grid:      
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5

pprgo:
  fixed:
    data_device: 'cpu'
    model_params:
      label: Vanilla PPRGo
      model: PPRGo
      ppr_normalization: 'row' 
      batch_norm: False
      topk: 128
      hidden_size: 256
      nlayers: 4
      alpha: 0.1
      eps: 1e-4
      dropout: 0.0

soft_median_rpprgo_t1_0:
  fixed:
    data_device: 'cpu'
    model_params:
      label: Soft Median RPPRGo (T=1.0)
      model: RobustPPRGo
      ppr_normalization: 'row' 
      batch_norm: True
      topk: 128
      hidden_size: 256
      alpha: 0.1
      eps: 1e-4
      dropout: 0.0
      nlayers: 4
      mean: soft_median
      mean_kwargs: 
        temperature: 1.0
    train_params:
      weight_decay: 5e-5

soft_median_rpprgo_t5_0:
  fixed:
    data_device: 'cpu'
    model_params:
      label: Soft Median RPPRGo (T=1.0)
      model: RobustPPRGo
      ppr_normalization: 'row' 
      batch_norm: True
      topk: 128
      hidden_size: 256
      alpha: 0.1
      eps: 1e-4
      dropout: 0.0
      nlayers: 4
      mean: soft_median
      mean_kwargs: 
        temperature: 1.0
    train_params:
      weight_decay: 5e-5
