seml:
  name: rgnn_papers100M_train
  executable: experiment_train.py
  project_root_dir: ../..
  output_dir: seml/train/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 200G
    cpus-per-task: 12  # num cores
    time: 1-12:00     # max time, D-HH:MM

fixed:
  data_dir: /nfs/students/schmidtt/datasets/
  train_params:
    lr: 1e-2
    weight_decay: 1e-3
    patience: 300
    max_epochs: 30
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0


grid:
  dataset:
    type: choice
    options:
      - ogbn-papers100M
  binary_attr:
    type: choice
    options:
      #- True
      - False
  seed:
    type: choice
    options:
      - 0
      # - 1
      # - 5
  model_params:
    type: parameter_collection 
    params:
      hidden_size:              # Size of the MLP's hidden layer
        type: choice
        options: [64, 128]
      nlayers:                   # Number of MLP layers
        type: choice
        options: [2, 3]
      alpha:                      # PPR teleport probability
        type: choice
        options: [0.5]
      mean_kwargs: 
        type: parameter_collection 
        params:
          temperature: 
            type: choice
            options: [5.0, 50.0]
      dropout:                      
        type: choice
        options: [0.1, 0.5]


soft_median_pprgo:
  fixed:
    model_params:
      label: Soft Median PPRGo
      model: RobustPPRGo
      ppr_normalization: 'row' 
      do_cache_adj_prep: True
      topk: 64
      eps: 1e-2
      mean: soft_median
    train_params:
      batch_size: 16384 # 16G
      batch_mult_val: 1
      forward_batch_size: 128
    data_device: cpu
    make_unweighted: True
    make_undirected: False
    normalize: False
