seml:
  name: rgnn_at_scale_train
  db_collection: rgnn_at_scale_train
  executable: experiment_train.py
  #conda_environment: rgnn_at_scale
  project_root_dir: ../..
  output_dir: seml/train/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-00:01     # max time, D-HH:MM

fixed:
  data_dir: /nfs/students/schmidtt/datasets/

rpprgo:
  fixed:
    model_params:
      label: Robust PPRGo
      model: RobustPPRGo
      ppr_normalization: 'row' 
      do_cache_adj_prep: True
      topk: 64
      hidden_size: 128
      nlayers: 2
      alpha: 0.5
      eps: 1e-2
      dropout: 0.25
      mean: soft_k_medoid
      mean_kwargs: 
        k: 64
        temperature: 50.0
        with_weight_correction: True

    dataset: ogbn-arxiv #  ogbn-papers100M #citeseer 
    binary_attr: False
    seed: 0
    train_params:
      lr: 1e-2
      weight_decay: 1e-3
      patience: 300
      max_epochs: 200
      batch_size: 10240
      forward_batch_size: 128
      batch_mult_val: 1
    artifact_dir: cache
    model_storage_type: pretrained
    device: cpu
    data_device: cpu
    make_unweighted: True
    make_undirected: False
    normalize: False
