seml:
  name: products_localprbcd
  executable: experiments/experiment_local_attack_direct.py
  project_root_dir: ../..
  output_dir: seml/attack_local/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 48G          # memory
    cpus-per-task: 4  # num cores
    time: 1-00:00     # max time, D-HH:MM
    #partition: cpu
    # qos: interactive
    # qos: studentpriocpu
    qos: studentprio
    

fixed:
  data_dir: datasets
  dataset: ogbn-products
  epsilons: [0.5, 1.0]
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0
  data_device: cpu
  debug_level: info
  nodes_topk: 40
  attack_params.epochs: 80
  attack_params.display_step: 1
  attack_params.fine_tune_epochs: 20
  attack_params.do_synchronize: True
  attack_params.ppr_recalc_at_end: True
  attack_params.ppr_cache_params:
    data_artifact_dir: cache
    data_storage_type: ppr

grid:
  seed:
    type: choice
    options:
      - 0
      # - 1
      # - 5
      # - 42
      # - 100
  

# localprbcd_pprgo:
#   fixed:
#     nodes_topk: 40
#     binary_attr: False
#     make_undirected: False
#     attack: LocalBatchedPRBCD
#     model_label: Vanilla PPRGo
#     attack_params.loss_type: Margin
#     attack_params.lr_factor: 0.5


localprbcd_GCN:
  fixed:
    nodes_topk: 40
    binary_attr: False
    make_undirected: True
    attack: LocalPRBCD
    model_label: Vanilla GCN
    attack_params.loss_type: Margin
    attack_params.lr_factor: 0.5

