seml:
  name: rgnn_at_scale_attack_evasion_global_transfer
  executable: experiments/experiment_global_attack_transfer.py
  project_root_dir: ../..
  output_dir: config/attack_evasion_global_transfer/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 4G          # memory
    cpus-per-task: 4  # num cores
    time: 0-01:00     # max time, D-HH:MM

fixed:
  data_dir: data/
  epsilons: [0, 0.05, 0.1, 0.25]
  artifact_dir: cache
  pert_adj_storage_type: evasion_global_transfer_adj
  pert_attr_storage_type: evasion_global_transfer_attr
  model_storage_type: pretrained
  surrogate_model_storage_type: pretrained
  device: 0
  data_device: 0
  make_undirected: True

grid:
  dataset: 
    type: choice
    options:
      - cora_ml
      - citeseer

  seed:
    type: choice
    options:
      - 0
      - 1
      - 5
      - 42
      - 100

fsgm:
  fixed:
    attack: FGSM
    attack_params:
      epochs: 300
      loss_type: MCE

pgd:
  fixed:
    attack: PGD
    attack_params: 
      epochs: 300
      loss_type: tanhMargin

greedy_rbcd:
  fixed:
    attack: GreedyRBCD
    surrogate_model_label: Vanilla GCN
  grid:
   attack_params: 
      type: choice
      options:
        - epochs: 50
          block_size: 2_000
          loss_type: MCE
        - epochs: 50
          block_size: 5_000
          loss_type: MCE
        - epochs: 50
          block_size: 10_000
          loss_type: MCE
        - epochs: 50
          block_size: 100_000
          loss_type: MCE
        - epochs: 50
          block_size: 1_000_000
          loss_type: MCE

prbcd:
  fixed:
    attack: PRBCD
    surrogate_model_label: Vanilla GCN
  grid:
    attack_params: 
      type: choice
      options:
        - epochs: 300
          fine_tune_epochs: 250
          block_size: 2_000
          loss_type: tanhMargin
        - epochs: 300
          fine_tune_epochs: 250
          block_size: 5_000
          loss_type: tanhMargin
        - epochs: 300
          fine_tune_epochs: 250
          block_size: 10_000
          loss_type: tanhMargin
        - epochs: 300
          fine_tune_epochs: 250
          block_size: 100_000
          loss_type: tanhMargin
        - epochs: 300
          fine_tune_epochs: 250
          block_size: 1_000_000
          loss_type: tanhMargin
        - epochs: 300
          fine_tune_epochs: 250
          block_size: 10_000_000
          loss_type: tanhMargin
