seml:
  name: rgnn_at_scale_attack_evasion_transfer_gang_degree
  db_collection: kdd21_rgnn_at_scale_attack_evasion_transfer_gang_degree
  executable: experiment_attack_evasion_transfer.py
  conda_environment: rgnn_at_scale
  project_root_dir: ../..
  output_dir: seml/attack_evasion_transfer/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-08:00     # max time, D-HH:MM

fixed:
  epsilons: [0, 0.1, 0.25]
  surrogate_params:
    n_filters: 64
    dropout: 0.5
    train_params:
      lr: 1e-2
      weight_decay: 1e-3
      patience: 100
      max_epochs: 3000
  artifact_dir: cache
  pert_adj_storage_type: evasion_transfer_attack_adj
  pert_attr_storage_type: evasion_transfer_attack_attr
  model_storage_type: pretrained
  device: 0
  binary_attr: True

grid:
  dataset: 
    type: choice
    options:
      - cora_ml

  seed:
    type: choice
    options:
      - 0
      - 1
      - 5
      - 42
      - 100

gang:
  fixed:
    attack: GANG
  
  grid:
    attack_params:
      type: choice
      options:
        - edge_budget: 5
          edge_step_size: 5
          feature_dedicated_iterations: 5
          edge_with_random_reverse: True
          feature_lr: 5e-1
          feature_greedy_opt: True
          eps: 1e-16
        - edge_budget: 10
          edge_step_size: 5
          feature_dedicated_iterations: 5
          edge_with_random_reverse: True
          feature_lr: 5e-1
          feature_greedy_opt: True
          eps: 1e-16
        - edge_budget: 20
          edge_step_size: 5
          feature_dedicated_iterations: 5
          edge_with_random_reverse: True
          feature_lr: 5e-1
          feature_greedy_opt: True
          eps: 1e-16
        - edge_budget: 50
          edge_step_size: 5
          feature_dedicated_iterations: 5
          edge_with_random_reverse: True
          feature_lr: 5e-1
          feature_greedy_opt: True
          eps: 1e-16
        - edge_budget: 100
          edge_step_size: 5
          feature_dedicated_iterations: 5
          edge_with_random_reverse: True
          feature_lr: 5e-1
          feature_greedy_opt: True
          eps: 1e-16
        - edge_budget: 200
          edge_step_size: 5
          feature_dedicated_iterations: 5
          edge_with_random_reverse: True
          feature_lr: 5e-1
          feature_greedy_opt: True
          eps: 1e-16