seml:
  name: rgnn_at_scale_attack_evasion_transfer
  db_collection: rgnn_at_scale_attack_evasion_transfer
  executable: experiment_attack_evasion_transfer.py
  conda_environment: rgnn_at_scale
  project_root_dir: ../..
  output_dir: seml/attack_evasion_transfer/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-08:00     # max time, D-HH:MM
    partition: gpu_large

fixed:
  epsilons: [0, 0.01, 0.05, 0.1, 0.25]
  surrogate_params:
    n_filters: 64
    dropout: 0.5
    train_params:
      lr: 1e-2
      weight_decay: 1e-3
      patience: 100
      max_epochs: 3000
  artifact_dir: cache
  pert_adj_storage_type: attack
  model_storage_type: pretrained
  device: 0
  binary_attr: False

grid:
  dataset:
    type: choice
    options:
      - pubmed

  seed:
    type: choice
    options:
      - 0
      - 1
      - 5

pgd:
  fixed:
    binary_attr: False
    attack: PGD

fgsm:
  fixed:
    binary_attr: False
    attack: FGSM

greedy_rbcd:
  fixed:
    binary_attr: False
    attack: GreedyRBCD

prbcd:
  fixed:
    binary_attr: False
    attack: PRBCD
    attack_params:
      keep_heuristic: WeightOnly
      search_space_size: 500_000
      do_synchronize: True

gang:
  fixed:
    binary_attr: True
    attack: GANG
    attack_params:
      edge_with_random_reverse: False
      edge_step_size: 25
      edge_budget: 50
      feature_dedicated_iterations: 5
      do_synchronize: True
      feature_lr: 5e-1
      feature_greedy_opt: True
      eps: 1e-16

dice:
  fixed:
    binary_attr: False
    attack: DICE