seml:
  name: products_dice
  executable: experiments/experiment_local_attack_direct.py
  project_root_dir: ../..
  output_dir: seml/attack_evasion_local_direct/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 48G          # memory
    cpus-per-task: 4  # num cores
    time: 0-12:00     # max time, D-HH:MM
    # partition: cpu
    # qos: studentpriocpu
    qos: studentprio

fixed:
  data_dir: datasets
  dataset: ogbn-products
  binary_attr: False
  model_storage_type: victim_products
  artifact_dir: cache
  nodes: None
  nodes_topk: 40
  device: 0
  data_device: cpu
  debug_level: info

grid:
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5
  make_undirected:
    type: choice
    options:
      # - True
      - False
  epsilons:
    type: choice
    options:
      - [0.05]
      - [0.1]
      - [0.25]
      #- [0.05, 0.1, 0.25]

# gcn_dice:
#   fixed:
#     attack: LocalDICE
#     model_label: Vanilla GCN

pprgo_localprbcd_seed0:
  fixed:
    attack: LocalDICE
    model_label: Vanilla PPRGo


meidan_1_0_pprgo_localprbcd:
  fixed:
    attack: LocalDICE
    model_label: Soft Median PPRGo (T=1.0)

meidan_5_0_pprgo_localprbcd:
  fixed:
    attack: LocalDICE
    model_label: Soft Median PPRGo (T=5.0)
