seml:
  name: rgnn_at_scale_attack_evasion_local_direct
  executable: experiments/experiment_local_attack_direct.py
  project_root_dir: ../..
  output_dir: seml/attack_evasion_local_direct/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 4  # num cores
    time: 0-08:00     # max time, D-HH:MM
   
fixed:
  data_dir: datasets/
  epsilons: [0.5, 0.75, 1]
  model_storage_type: pretrained
  pert_adj_storage_type: evasion_local_attack_adj
  pert_attr_storage_type: evasion_local_attack_attr
  artifact_dir: cache
  display_steps: 20
  nodes: None
  device: 0
  data_device: cpu
  binary_attr: False
  normalize: False
  normalize_attr: False
  make_unweighted: True
  make_undirected: True

  dataset: ogbn-products

grid:
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5
  
  make_undirected: 
    type: choice
    options:
      # - False
      - True

gcn:
  fixed:
    model_label: Vanilla GCN
    artifact_dir: /nfs/homedirs/geisler/code/robust_gnns_at_scale/cache
    binary_attr: False
    attack: LocalPRBCD
    attack_params:
      epochs: 250
      fine_tune_epochs: 50
      lr_factor: 0.05
      search_space_size: 50_000
      ppr_recalc_at_end: False

localprbcd_vanillapprgo:
  fixed:
    binary_attr: False
    attack: LocalPRBCD
    model_label: Vanilla PPRGo
    attack_params:
      epochs: 250
      fine_tune_epochs: 50
      lr_factor: 0.05
      search_space_size: 50_000
      ppr_recalc_at_end: False

localprbcd_softmedianpprgo:
  fixed:
    binary_attr: False
    attack: LocalPRBCD
    model_label: Soft Median RPPRGo (T=5.0)
    make_undirected: False
    attack_params:
      epochs: 250
      fine_tune_epochs: 50
      lr_factor: 0.1
      search_space_size: 20_000
      ppr_recalc_at_end: False
