seml:
  name: products_localprbcd
  executable: experiments/experiment_local_attack_direct.py
  project_root_dir: ../..
  output_dir: seml/attack_evasion_local_direct/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 24G          # memory
    cpus-per-task: 4  # num cores
    time: 1-00:00     # max time, D-HH:MM
    partition: gpu_large
    

fixed:
  data_dir: datasets
  dataset: ogbn-products
  epsilons: [0.5, 1.0]
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0
  data_device: cpu
  debug_level: info
  nodes_topk: 40
  attack_params.epochs: 30
  attack_params.fine_tune_epochs: 5
  attack_params.display_step: 2
  attack_params.do_synchronize: True

grid:
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5
      # - 42
      # - 100
    
  make_undirected: 
    type: choice
    options:
      - False
      # - True


localprbcd_GCN:
  fixed:
    binary_attr: False
    attack: LocalPRBCD
    model_label: Vanilla GCN (surrogate)
    attack_params.loss_type: Margin
    attack_params.search_space_size: 20_000
    attack_params.lr_factor: 0.05

