name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install Pytorch for CPU
      run: |
        conda install pytorch==1.8.1 torchvision torchaudio cpuonly -c pytorch
    - name: Install dependencies and actual module
      run: |
        # Install requirements
        pip install -r requirements.txt
        # Install development requirements
        # pip install -r requirements-dev.txt
        # Install actual module
        pip install .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Static analysis with pydocstyle
      run: |
        pip install pydocstyle
        pydocstyle
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
