name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.7.13"
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install Pytorch 1.8.1 for CPU
      run: |
        conda install python==3.7.13
        conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cpuonly -c pytorch
    - name: Install dependencies and actual module
      run: |
        # Install requirements
        pip install -r requirements.txt
        # Install development requirements
        pip install -r requirements-dev.txt
        # Install actual module
        pip install .
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    - name: Static analysis with pydocstyle
      run: |
        pip install pydocstyle
        pydocstyle .
    - name: Test with pytest
      run: |
        pip install pytest
        python -m pytest tests/
