seml:
  name: rgnn_at_scale_attack_evasion_local_transfer
  executable: experiments/experiment_local_attack_transfer.py
  project_root_dir: ../..
  output_dir: config/attack_evasion_local_transfer/output

slurm:
  experiments_per_job: 4
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 1-00:00     # max time, D-HH:MM

fixed:
  data_dir: data/
  model_storage_type: pretrained
  surrogate_model_storage_type: pretrained
  artifact_dir: cache
  nodes: None
  nodes_topk: 40
  device: 0
  data_device: cpu
  binary_attr: False
  attack: LocalPRBCD
  evaluate_poisoning: True

grid:
  epsilons:
    type: choice
    options:
      - [0.1]
      - [0.25]
      - [0.5]
      - [0.75]
      - [1.0]

  dataset:
    type: choice
    options:
      - cora_ml
      - citeseer

  seed:
    type: choice
    options:
      - 0
      - 1
      - 5

# gcn:
#   fixed:
#     model_label: Vanilla GCN
#     surrogate_model_label: Vanilla GCN
#     make_undirected: True
#     attack_params:
#       lr_factor: 0.05

# gcn_sgc_surrogate:
#   fixed:
#     model_label: Vanilla GCN
#     surrogate_model_label: Vanilla SGC
#     make_undirected: True
#     attack_params:
#       lr_factor: 0.05

# gcn_directed:
#   fixed:
#     model_label: Vanilla GCN
#     surrogate_model_label: Vanilla GCN
#     model_storage_type: pretrained_rownorm
#     surrogate_model_storage_type: pretrained_rownorm
#     make_undirected: False
    # attack_params:
    #   lr_factor: 0.05

# vanilla_pprgo_with_surrogate:
#   fixed:
#     model_label: Vanilla PPRGo
#     surrogate_model_label: Vanilla GCN
#     attack_params:
#       lr_factor: 0.05
#   grid:
#     make_undirected:
#       type: choice
#       options:
#         - True
#         # - False

# softmedian_pprgo_with_surrogate:
#   fixed:
#     model_label: Soft Median PPRGo (T=1.0)
#     surrogate_model_label: Vanilla GCN
#     attack_params:
#       lr_factor: 0.05
#   grid:
#     make_undirected:
#       type: choice
#       options:
#         - True
#         # - False

# vanilla_pprgo_no_surrogate:
#   fixed:
#     model_label: Vanilla PPRGo
#     surrogate_model_label: Vanilla PPRGo
#     attack: LocalBatchedPRBCD
#     attack_params:
#       lr_factor: 0.05
#       ppr_recalc_at_end: True
#   grid:
#     make_undirected:
#       type: choice
#       options:
#         - True
#         # - False

# softmedian_pprgo_no_surrogate:
#   fixed:
#     model_label: Soft Median PPRGo (T=1.0)
#     surrogate_model_label: Soft Median PPRGo (T=1.0)
#     attack: LocalBatchedPRBCD
#     attack_params:
#       lr_factor: 0.25
#       ppr_recalc_at_end: True
#   grid:
#     make_undirected:
#       type: choice
#       options:
#         - True
#         # - False

# vanilla_sgc_with_surrogate:
#   fixed:
#     model_label: Vanilla SGC
#     surrogate_model_label: Vanilla GCN
#     attack_params:
#       lr_factor: 0.05
#     make_undirected: True

vanilla_sgc_no_surrogate:
  fixed:
    model_label: Vanilla SGC
    surrogate_model_label: Vanilla SGC
    attack_params:
      lr_factor: 0.05
    make_undirected: True
    artifact_dir: cache_tobias

# vanilla_gdc_gcn_surrogate:
#   fixed:
#     model_label: Vanilla GDC
#     surrogate_model_label: Vanilla GCN
#     make_undirected: True
#     attack_params:
#       lr_factor: 0.05

# vanilla_gdc_sgc_surrogate:
#   fixed:
#     model_label: Vanilla GDC
#     surrogate_model_label: Vanilla SGC
#     make_undirected: True
#     attack_params:
#       lr_factor: 0.05

# vanilla_gdc_no_surrogate:
#   fixed:
#     model_label: Vanilla GDC
#     surrogate_model_label: Vanilla GDC
#     make_undirected: True
#     attack_params:
#       lr_factor: 0.05

# vanilla_gat_no_surrogate:
#   fixed:
#     model_label: Vanilla GAT
#     surrogate_model_label: Vanilla GAT
#     make_undirected: True
#     attack_params:
#       lr_factor: 0.05

# vanilla_gat_gcn_surrogate:
#   fixed:
#     model_label: Vanilla GAT
#     surrogate_model_label: Vanilla GCN
#     make_undirected: True
#     attack_params:
#       lr_factor: 0.05

# vanilla_gat_sgc_surrogate:
#   fixed:
#     model_label: Vanilla GAT
#     surrogate_model_label: Vanilla SGC
#     make_undirected: True
#     attack_params:
#       lr_factor: 0.05